\doxysection{jpl\+::\+\_\+exception\+::Arithmetic\+Exception Class Reference}
\hypertarget{classjpl_1_1__exception_1_1ArithmeticException}{}\label{classjpl_1_1__exception_1_1ArithmeticException}\index{jpl::\_exception::ArithmeticException@{jpl::\_exception::ArithmeticException}}


{\ttfamily \#include $<$Arithmetic\+Exception.\+hpp$>$}

Inheritance diagram for jpl\+::\+\_\+exception\+::Arithmetic\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=4.000000cm]{d6/d9d/classjpl_1_1__exception_1_1ArithmeticException}
\end{center}
\end{figure}
\doxysubsubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classjpl_1_1__exception_1_1ArithmeticException_a688c59db20e0b009dc1e09ea298002e2_a688c59db20e0b009dc1e09ea298002e2}{Arithmetic\+Exception}} (std\+::string \mbox{\hyperlink{classjpl_1_1__exception_1_1AbstractException_a2aa9aba38aab837ce8eee9552dd2f1fb_a2aa9aba38aab837ce8eee9552dd2f1fb}{msg}})
\item 
\mbox{\hyperlink{classjpl_1_1__exception_1_1ArithmeticException_aae632cd5cb0fd2e4eb960e1a72db3bcb_aae632cd5cb0fd2e4eb960e1a72db3bcb}{Arithmetic\+Exception}} ()
\item 
virtual const char \texorpdfstring{$\ast$}{*} \mbox{\hyperlink{classjpl_1_1__exception_1_1AbstractException_ae17527e3192e5afdb01a90f199dbafe5_ae17527e3192e5afdb01a90f199dbafe5}{what}} () const \+\_\+\+GLIBCXX\+\_\+\+TXN\+\_\+\+SAFE\+\_\+\+DYN \+\_\+\+GLIBCXX\+\_\+\+NOTHROW override
\begin{DoxyCompactList}\small\item\em Print the type of the exception which has been thrown with the message that has been passed, too. \end{DoxyCompactList}\end{DoxyCompactItemize}
\doxysubsubsection*{Protected Attributes}
\begin{DoxyCompactItemize}
\item 
std\+::string \mbox{\hyperlink{classjpl_1_1__exception_1_1AbstractException_ac135cf56b3dc4fdb4bc558d345d0f436_ac135cf56b3dc4fdb4bc558d345d0f436}{type\+\_\+ex}}
\item 
std\+::string \mbox{\hyperlink{classjpl_1_1__exception_1_1AbstractException_a2aa9aba38aab837ce8eee9552dd2f1fb_a2aa9aba38aab837ce8eee9552dd2f1fb}{msg}}
\end{DoxyCompactItemize}


\doxysubsection{Constructor \& Destructor Documentation}
\Hypertarget{classjpl_1_1__exception_1_1ArithmeticException_a688c59db20e0b009dc1e09ea298002e2_a688c59db20e0b009dc1e09ea298002e2}\label{classjpl_1_1__exception_1_1ArithmeticException_a688c59db20e0b009dc1e09ea298002e2_a688c59db20e0b009dc1e09ea298002e2} 
\index{jpl::\_exception::ArithmeticException@{jpl::\_exception::ArithmeticException}!ArithmeticException@{ArithmeticException}}
\index{ArithmeticException@{ArithmeticException}!jpl::\_exception::ArithmeticException@{jpl::\_exception::ArithmeticException}}
\doxysubsubsection{\texorpdfstring{ArithmeticException()}{ArithmeticException()}\hspace{0.1cm}{\footnotesize\ttfamily [1/2]}}
{\footnotesize\ttfamily jpl\+::\+\_\+exception\+::\+Arithmetic\+Exception\+::\+Arithmetic\+Exception (\begin{DoxyParamCaption}\item[{std\+::string}]{msg }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}

\Hypertarget{classjpl_1_1__exception_1_1ArithmeticException_aae632cd5cb0fd2e4eb960e1a72db3bcb_aae632cd5cb0fd2e4eb960e1a72db3bcb}\label{classjpl_1_1__exception_1_1ArithmeticException_aae632cd5cb0fd2e4eb960e1a72db3bcb_aae632cd5cb0fd2e4eb960e1a72db3bcb} 
\index{jpl::\_exception::ArithmeticException@{jpl::\_exception::ArithmeticException}!ArithmeticException@{ArithmeticException}}
\index{ArithmeticException@{ArithmeticException}!jpl::\_exception::ArithmeticException@{jpl::\_exception::ArithmeticException}}
\doxysubsubsection{\texorpdfstring{ArithmeticException()}{ArithmeticException()}\hspace{0.1cm}{\footnotesize\ttfamily [2/2]}}
{\footnotesize\ttfamily jpl\+::\+\_\+exception\+::\+Arithmetic\+Exception\+::\+Arithmetic\+Exception (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}



\doxysubsection{Member Function Documentation}
\Hypertarget{classjpl_1_1__exception_1_1AbstractException_ae17527e3192e5afdb01a90f199dbafe5_ae17527e3192e5afdb01a90f199dbafe5}\label{classjpl_1_1__exception_1_1AbstractException_ae17527e3192e5afdb01a90f199dbafe5_ae17527e3192e5afdb01a90f199dbafe5} 
\index{jpl::\_exception::ArithmeticException@{jpl::\_exception::ArithmeticException}!what@{what}}
\index{what@{what}!jpl::\_exception::ArithmeticException@{jpl::\_exception::ArithmeticException}}
\doxysubsubsection{\texorpdfstring{what()}{what()}}
{\footnotesize\ttfamily virtual const char \texorpdfstring{$\ast$}{*} jpl\+::\+\_\+exception\+::\+Abstract\+Exception\+::what (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption}) const\hspace{0.3cm}{\ttfamily [inline]}, {\ttfamily [override]}, {\ttfamily [virtual]}, {\ttfamily [inherited]}}

\begin{DoxyReturn}{Returns}
const char\texorpdfstring{$\ast$}{*} 
\end{DoxyReturn}


Reimplemented in \mbox{\hyperlink{classjpl_1_1__exception_1_1IllegalCastException_a1a3a798cacf8456d77cd291b32c33e01_a1a3a798cacf8456d77cd291b32c33e01}{jpl\+::\+\_\+exception\+::\+Illegal\+Cast\+Exception}}, \mbox{\hyperlink{classjpl_1_1__exception_1_1IndexOutOfBoundsException_af6f4ef79c0585fb2a32b80d8991c7758_af6f4ef79c0585fb2a32b80d8991c7758}{jpl\+::\+\_\+exception\+::\+Index\+Out\+Of\+Bounds\+Exception}}, \mbox{\hyperlink{classjpl_1_1__exception_1_1IOException_a99b59a19d9d9165575e98678db8602f5_a99b59a19d9d9165575e98678db8602f5}{jpl\+::\+\_\+exception\+::\+IOException}}, and \mbox{\hyperlink{classjpl_1_1__exception_1_1SocketException_abd14ed90cb038701b335bc72fa8eeb4d_abd14ed90cb038701b335bc72fa8eeb4d}{jpl\+::\+\_\+exception\+::\+Socket\+Exception}}.



\doxysubsection{Field Documentation}
\Hypertarget{classjpl_1_1__exception_1_1AbstractException_a2aa9aba38aab837ce8eee9552dd2f1fb_a2aa9aba38aab837ce8eee9552dd2f1fb}\label{classjpl_1_1__exception_1_1AbstractException_a2aa9aba38aab837ce8eee9552dd2f1fb_a2aa9aba38aab837ce8eee9552dd2f1fb} 
\index{jpl::\_exception::ArithmeticException@{jpl::\_exception::ArithmeticException}!msg@{msg}}
\index{msg@{msg}!jpl::\_exception::ArithmeticException@{jpl::\_exception::ArithmeticException}}
\doxysubsubsection{\texorpdfstring{msg}{msg}}
{\footnotesize\ttfamily std\+::string jpl\+::\+\_\+exception\+::\+Abstract\+Exception\+::msg\hspace{0.3cm}{\ttfamily [protected]}, {\ttfamily [inherited]}}

It is a description of what has just happened. For some exception it may be a template of stuff (usually when constructor does not need any msg) \Hypertarget{classjpl_1_1__exception_1_1AbstractException_ac135cf56b3dc4fdb4bc558d345d0f436_ac135cf56b3dc4fdb4bc558d345d0f436}\label{classjpl_1_1__exception_1_1AbstractException_ac135cf56b3dc4fdb4bc558d345d0f436_ac135cf56b3dc4fdb4bc558d345d0f436} 
\index{jpl::\_exception::ArithmeticException@{jpl::\_exception::ArithmeticException}!type\_ex@{type\_ex}}
\index{type\_ex@{type\_ex}!jpl::\_exception::ArithmeticException@{jpl::\_exception::ArithmeticException}}
\doxysubsubsection{\texorpdfstring{type\_ex}{type\_ex}}
{\footnotesize\ttfamily std\+::string jpl\+::\+\_\+exception\+::\+Abstract\+Exception\+::type\+\_\+ex\hspace{0.3cm}{\ttfamily [protected]}, {\ttfamily [inherited]}}

This is a description of the exception which has been thrown. It is passed by constructor and it is as the exception name 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
exception/src/runtime/\mbox{\hyperlink{ArithmeticException_8hpp}{Arithmetic\+Exception.\+hpp}}\end{DoxyCompactItemize}
